version: "3"

services:
  db:
    container_name: PostgreSQL_DB
    image: postgres:10.3-alpine
    restart: always
    stop_signal: SIGINT  # Fast shutdown.
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5433
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    networks:
      - nestoras
  simple-ecommerce:
    build: ./simple-ecommerce
    container_name: Simple-Ecommerce
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 1149 -b '0.0.0.0'"
    environment:
      - DATABASE_URL=postgres://postgres@db
    volumes:
      - ./simple-ecommerce:/app:cached
      - /app/node_modules
    ports:
      - 1149:1149
    depends_on:
      - db
    networks:
      - nestoras
    links:
      - mailcatcher
    stdin_open: true
    tty: true

  mailcatcher:
    container_name: Mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    networks:
      - nestoras

volumes:
  db_data:
networks:
  nestoras:
    driver: bridge
