#!/bin/bash

set -euo pipefail

for i in erm,erm simple-ecommerce,simple-ecommerce esscentials,esscentials; do
    IFS=',' read -r name repo <<< "${i}"

    printf "\n\U1F4D8 Updating %s..." "${name}"
	# Clone or pull changes
	if [ -d "$name" ]; then
        echo "Pulling changes..."
		pushd "$name"
		git pull "git@github.com:NestorasRose/$repo.git"
        popd
	else
        echo "Cloning repository..."
		git clone "git@github.com:NestorasRose/$repo.git" "$name"
	fi
done
